save_dir: saved_model
normal_class: ["backrestdefect_half","chair104","no_backrest","no_roller_5", "no_legs_lowerpart"] #backrestdefect_half,"chair104","no_backrest","no_roller_5", "no_legs_lowerpart"
abnormal_class: ["airplane"]

root_path: data/to_mnt #mntはランダム

model: SkipVariationalFoldingNet
weight: [1.0, 1.0, 1.0, 1.0]
reconstruction_loss: CD
rotate: True
jitter: False
translate: False
batch_size: 40
test_batch_size: 100
num_epochs: 300

shape: sphere
feat_dims: 512
n_points: 2048

name: sample