save_dir: saved_model
normal_class: ["lamp","chair","table","car","sofa","airplane"]
abnormal_class: ["rifle"]

root_path: data 

model: SkipVariationalFoldingNet
weight: [1.0, 1.0, 1.0, 1.0]
reconstruction_loss: CD
rotate: True
jitter: False
translate: False
batch_size: 20
test_batch_size: 100
num_epochs: 300

shape: sphere
feat_dims: 512
n_points: 2048

name: sample

modeltype: VAE